/**
 * Build Script for AI Bot Release
 * Сборка обфусцированного .exe с лицензионной защитой
 * Использует esbuild для создания единого bundle
 */

const fs = require('fs-extra');
const path = require('path');
const { execSync } = require('child_process');
const JavaScriptObfuscator = require('javascript-obfuscator');
const esbuild = require('esbuild');

// Конфигурация сборки
const BUILD_CONFIG = {
  sourceDir: path.join(__dirname, '..'),
  releaseDir: path.join(__dirname, '..', 'Release'),
  tempDir: path.join(__dirname, '..', 'Release', 'temp_build'),
  bundleFile: 'bundle.js',
  obfuscatedFile: 'app.js',
  entryPoint: 'index.js',
  outputExe: 'AIBot.exe',
  nodeVersion: '18'  // Целевая версия Node.js для pkg
};

// Цвета для консоли
const colors = {
  reset: '\x1b[0m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  magenta: '\x1b[35m',
  cyan: '\x1b[36m',
  white: '\x1b[37m'
};

function log(message, color = 'white') {
  console.log(colors[color] + message + colors.reset);
}

function logStep(stepNum, message) {
  console.log('\n' + colors.cyan + `[${stepNum}/7]` + colors.reset + ' ' + colors.yellow + message + colors.reset);
}

function logSuccess(message) {
  console.log(colors.green + '✓ ' + message + colors.reset);
}

function logError(message) {
  console.log(colors.red + '✗ ' + message + colors.reset);
}

/**
 * Шаг 1: Очистка и создание папки Release
 */
async function prepareReleaseFolder() {
  logStep(1, 'Preparing Release folder...');
  
  try {
    // Удаляем старую папку если существует
    if (fs.existsSync(BUILD_CONFIG.releaseDir)) {
      await fs.remove(BUILD_CONFIG.releaseDir);
      log('Cleaned old Release folder');
    }
    
    // Создаем новые папки
    await fs.ensureDir(BUILD_CONFIG.releaseDir);
    await fs.ensureDir(BUILD_CONFIG.tempDir);
    
    logSuccess('Release folder prepared');
    return true;
  } catch (error) {
    logError(`Failed to prepare Release folder: ${error.message}`);
    return false;
  }
}

/**
 * Шаг 2: Подготовка обфусцированной версии
 */
async function obfuscateCode() {
  logStep(2, 'Obfuscating source code...');
  
  try {
    // Находим все JS файлы (кроме node_modules и скриптов сборки)
    const pattern = path.join(BUILD_CONFIG.sourceDir, '**/*.js');
    const files = glob.sync(pattern, {
      ignore: [
        '**/node_modules/**',
        '**/Release/**',
        '**/scripts/build.js',
        '**/scripts/license-check.js',
        '**/*.test.js'
      ]
    });
    
    log(`Found ${files.length} JavaScript files to obfuscate`);
    
    // Создаем entry point с лицензионной проверкой
    const licenseWrapper = generateLicenseWrapper();
    await fs.writeFile(path.join(BUILD_CONFIG.obfuscatedDir, 'index.js'), licenseWrapper);
    
    let processedCount = 0;
    let errorCount = 0;
    
    for (const filePath of files) {
      try {
        const relativePath = path.relative(BUILD_CONFIG.sourceDir, filePath);
        const outputPath = path.join(BUILD_CONFIG.obfuscatedDir, relativePath);
        
        // Читаем исходный код
        const code = await fs.readFile(filePath, 'utf8');
        
        // Обфусцируем
        const obfuscated = JavaScriptObfuscator.obfuscate(code, getObfuscationOptions(relativePath));
        
        // Создаем директории если нужно
        await fs.ensureDir(path.dirname(outputPath));
        
        // Пишем обфусцированный код
        await fs.writeFile(outputPath, obfuscated.getObfuscatedCode());
        
        processedCount++;
        
        if (processedCount % 10 === 0) {
          process.stdout.write('.');
        }
      } catch (error) {
        // Если файл нельзя обфусцировать (например, бинарный или с ошибками), копируем как есть
        try {
          const relativePath = path.relative(BUILD_CONFIG.sourceDir, filePath);
          const outputPath = path.join(BUILD_CONFIG.obfuscatedDir, relativePath);
          await fs.ensureDir(path.dirname(outputPath));
          await fs.copy(filePath, outputPath);
          errorCount++;
        } catch (copyError) {
          logError(`Failed to process ${filePath}: ${copyError.message}`);
        }
      }
    }
    
    console.log(''); // New line after dots
    logSuccess(`Obfuscation complete: ${processedCount} files processed${errorCount > 0 ? `, ${errorCount} copied as-is` : ''}`);
    return true;
  } catch (error) {
    logError(`Obfuscation failed: ${error.message}`);
    return false;
  }
}

/**
 * Генерация wrapper с лицензионной проверкой
 */
function generateLicenseWrapper() {
  return `/**
 * AI Bot - License Protected Entry Point
 * Auto-generated by build script
 */

const path = require('path');
const fs = require('fs');

// Встраиваем license-check модуль для работы в скомпилированном виде
const axios = require('axios');
const os = require('os');
const crypto = require('crypto');

// ====== КОНФИГУРАЦИЯ KEYAUTH (ЗАПОЛНИ ПЕРЕД РАСПРОСТРАНЕНИЕМ) ======
const KEYAUTH_CONFIG = {
  appName: 'Nullbit',           // <-- ВСТАВЬ СЮДА
  ownerId: '47IOqyDjNC',           // <-- ВСТАВЬ СЮДА
  appSecret: 'daf5f53ecdce23b1872224572b0e1b128288d6fde5ed95b26c07666a5331e6b6',         // <-- ВСТАВЬ СЮДА
  version: '1.0'
};

const colors = {
  reset: '\\x1b[0m',
  red: '\\x1b[31m',
  green: '\\x1b[32m',
  yellow: '\\x1b[33m',
  cyan: '\\x1b[36m'
};

function generateHWID() {
  try {
    const interfaces = os.networkInterfaces();
    let macAddress = '';
    for (const name of Object.keys(interfaces)) {
      for (const iface of interfaces[name]) {
        if (iface.mac && iface.mac !== '00:00:00:00:00:00' && !iface.internal) {
          macAddress = iface.mac;
          break;
        }
      }
      if (macAddress) break;
    }
    const cpuInfo = os.cpus()[0]?.model || 'unknown';
    const hwidString = macAddress + '-' + cpuInfo + '-' + os.hostname();
    return crypto.createHash('sha256').update(hwidString).digest('hex').substring(0, 32);
  } catch (error) {
    return crypto.createHash('sha256').update(os.hostname() + os.platform() + os.arch()).digest('hex').substring(0, 32);
  }
}

async function initSession() {
  try {
    const response = await axios.get('https://keyauth.win/api/1.2/', {
      params: {
        type: 'init',
        name: KEYAUTH_CONFIG.appName,
        ownerid: KEYAUTH_CONFIG.ownerId,
        version: KEYAUTH_CONFIG.version
      },
      timeout: 15000
    });
    const data = response.data;
    if (data.success && data.sessionid) {
      return { success: true, sessionid: data.sessionid };
    } else {
      return { success: false, message: data.message || 'Failed to initialize session' };
    }
  } catch (error) {
    return { success: false, message: 'Session init error: ' + error.message };
  }
}

async function verifyLicense(licenseKey) {
  if (!KEYAUTH_CONFIG.appName || !KEYAUTH_CONFIG.ownerId || !KEYAUTH_CONFIG.appSecret) {
    return { success: false, message: 'KeyAuth not configured' };
  }
  if (!licenseKey || licenseKey.trim() === '') {
    return { success: false, message: 'License key not found in config.json' };
  }
  // Step 1: Initialize session
  const sessionResult = await initSession();
  if (!sessionResult.success) {
    return { success: false, message: 'Failed to initialize session: ' + sessionResult.message };
  }
  const sessionid = sessionResult.sessionid;
  const hwid = generateHWID();
  try {
    // Step 2: Verify license with sessionid
    const response = await axios.post('https://keyauth.win/api/1.2/', {
      type: 'license',
      key: licenseKey.trim(),
      hwid: hwid,
      sessionid: sessionid,
      name: KEYAUTH_CONFIG.appName,
      ownerid: KEYAUTH_CONFIG.ownerId,
      secret: KEYAUTH_CONFIG.appSecret,
      version: KEYAUTH_CONFIG.version
    }, { headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, timeout: 15000 });
    
    const data = response.data;
    if (data.success) {
      return { success: true, message: 'License verified', data: { username: data.info?.username, hwid: hwid } };
    } else {
      let errorMessage = data.message || 'Unknown error';
      if (errorMessage.toLowerCase().includes('hwid')) {
        errorMessage = 'HWID mismatch! Your key is bound to another device. Contact support. HWID: ' + hwid;
      }
      return { success: false, message: errorMessage };
    }
  } catch (error) {
    return { success: false, message: 'Network error: ' + error.message };
  }
}

function printBanner(result) {
  console.log('\\n' + colors.cyan + '╔════════════════════════════════════════════════════════╗' + colors.reset);
  console.log(colors.cyan + '║' + colors.reset + '           AI Bot - License Verification              ' + colors.cyan + '║' + colors.reset);
  console.log(colors.cyan + '╠════════════════════════════════════════════════════════╣' + colors.reset);
  if (result.success) {
    console.log(colors.cyan + '║' + colors.green + '  ✅ License: VERIFIED                                 ' + colors.cyan + '║' + colors.reset);
    console.log(colors.cyan + '║' + colors.reset + '  👤 User: ' + (result.data?.username || 'N/A').padEnd(35) + colors.cyan + '║' + colors.reset);
    console.log(colors.cyan + '╚════════════════════════════════════════════════════════╝' + colors.reset);
    console.log(colors.green + '\\n✓ Starting bot...\\n' + colors.reset);
  } else {
    console.log(colors.cyan + '║' + colors.red + '  ❌ License: FAILED                                    ' + colors.cyan + '║' + colors.reset);
    console.log(colors.cyan + '║' + colors.reset + '  📝 ' + (result.message.substring(0, 46) || 'Unknown').padEnd(46) + colors.cyan + '║' + colors.reset);
    console.log(colors.cyan + '╚════════════════════════════════════════════════════════╝' + colors.reset);
    console.log(colors.red + '\\n✗ ' + result.message + '\\n' + colors.reset);
  }
}

async function checkLicense() {
  try {
    const configPath = path.join(process.cwd(), 'config.json');
    if (!fs.existsSync(configPath)) {
      printBanner({ success: false, message: 'config.json not found in ' + process.cwd() });
      return false;
    }
    const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
    if (!config.license_key) {
      printBanner({ success: false, message: 'license_key not found in config.json' });
      return false;
    }
    const result = await verifyLicense(config.license_key);
    printBanner(result);
    return result.success;
  } catch (error) {
    printBanner({ success: false, message: error.message });
    return false;
  }
}

// ====== ЗАГРУЗКА ОСНОВНОГО БОТА ======
async function startBot() {
  const licenseValid = await checkLicense();
  if (!licenseValid) {
    console.log(colors.red + '\\nPress any key to exit...' + colors.reset);
    process.stdin.setRawMode(true);
    process.stdin.resume();
    process.stdin.on('data', () => process.exit(1));
    setTimeout(() => process.exit(1), 5000);
    return;
  }
  
  // Загружаем основной бот
  try {
    require('./startBot.js');
  } catch (error) {
    console.error('Failed to start bot:', error.message);
    process.exit(1);
  }
}

startBot();
`;
}

/**
 * Получение настроек обфускации
 * Настройки выбраны для баланса защиты и производительности (50ms тикрейт)
 */
function getObfuscationOptions(filePath) {
  // Для критичных к производительности файлов (PvP) — легкая обфускация
  const isPerformanceCritical = filePath.includes('PvPMode') || 
                                filePath.includes('CombatSystem') ||
                                filePath.includes('physics') ||
                                filePath.includes('tick');
  
  if (isPerformanceCritical) {
    return {
      compact: true,
      controlFlowFlattening: false,
      deadCodeInjection: false,
      debugProtection: false,
      disableConsoleOutput: false,
      identifierNamesGenerator: 'mangled',
      renameGlobals: false,
      rotateStringArray: true,
      selfDefending: true,
      stringArray: true,
      stringArrayEncoding: ['base64'],
      stringArrayThreshold: 0.5,
      unicodeEscapeSequence: false,
      // Сохраняем производительность
      simplify: true,
      numbersToExpressions: false
    };
  }
  
  // Для остальных файлов — средняя обфускация
  return {
    compact: true,
    controlFlowFlattening: true,
    controlFlowFlatteningThreshold: 0.3,
    deadCodeInjection: true,
    deadCodeInjectionThreshold: 0.2,
    debugProtection: true,
    debugProtectionInterval: 2000,
    disableConsoleOutput: false,
    identifierNamesGenerator: 'hexadecimal',
    renameGlobals: true,
    rotateStringArray: true,
    selfDefending: true,
    stringArray: true,
    stringArrayEncoding: ['rc4', 'base64'],
    stringArrayThreshold: 0.75,
    transformObjectKeys: true,
    unicodeEscapeSequence: false,
    // Баланс производительности
    simplify: true,
    numbersToExpressions: true,
    numbersToExpressionsThreshold: 0.3
  };
}

/**
 * Шаг 3: Копирование package.json и установка зависимостей
 */
async function preparePackageJson() {
  logStep(3, 'Preparing package.json for build...');
  
  try {
    // Читаем оригинальный package.json
    const pkgPath = path.join(BUILD_CONFIG.sourceDir, 'package.json');
    const pkg = await fs.readJson(pkgPath);
    
    // Модифицируем для релиза
    const releasePkg = {
      name: pkg.name,
      version: pkg.version,
      main: 'index.js',
      bin: 'index.js',
      pkg: {
        scripts: ['**/*.js'],
        assets: [
          'config/**/*',
          'voice/**/*',
          'node_modules/**/*',
          'patches/**/*'
        ],
        targets: [`node${BUILD_CONFIG.nodeVersion}-win-x64`],
        outputPath: '.'
      },
      dependencies: pkg.dependencies
    };
    
    // Добавляем axios если его нет
    if (!releasePkg.dependencies.axios) {
      releasePkg.dependencies.axios = '^1.6.0';
    }
    
    // Пишем в обфусцированную папку
    await fs.writeJson(path.join(BUILD_CONFIG.obfuscatedDir, 'package.json'), releasePkg, { spaces: 2 });
    
    // Копируем критичные файлы
    const filesToCopy = [
      'patches',
      'voice',
      'config'
    ];
    
    for (const file of filesToCopy) {
      const src = path.join(BUILD_CONFIG.sourceDir, file);
      const dest = path.join(BUILD_CONFIG.obfuscatedDir, file);
      if (fs.existsSync(src)) {
        await fs.copy(src, dest);
      }
    }
    
    logSuccess('package.json prepared');
    return true;
  } catch (error) {
    logError(`Failed to prepare package.json: ${error.message}`);
    return false;
  }
}

/**
 * Шаг 4: Установка зависимостей
 */
async function installDependencies() {
  logStep(4, 'Installing dependencies...');
  
  try {
    log('Running npm install in obfuscated directory...');
    execSync('npm install --production', {
      cwd: BUILD_CONFIG.obfuscatedDir,
      stdio: 'pipe'
    });
    
    logSuccess('Dependencies installed');
    return true;
  } catch (error) {
    logError(`Failed to install dependencies: ${error.message}`);
    return false;
  }
}

/**
 * Шаг 5: Сборка с помощью pkg
 */
async function buildExecutable() {
  logStep(5, 'Building executable with pkg...');
  
  try {
    const pkgCommand = `npx pkg . --targets node${BUILD_CONFIG.nodeVersion}-win-x64 --output ${path.join(BUILD_CONFIG.releaseDir, BUILD_CONFIG.outputExe)}`;
    
    log('Running: ' + pkgCommand);
    
    execSync(pkgCommand, {
      cwd: BUILD_CONFIG.obfuscatedDir,
      stdio: 'inherit'
    });
    
    logSuccess(`Executable built: ${BUILD_CONFIG.outputExe}`);
    return true;
  } catch (error) {
    logError(`Build failed: ${error.message}`);
    return false;
  }
}

/**
 * Шаг 6: Создание шаблона config.json
 */
async function createConfigTemplate() {
  logStep(6, 'Creating config.json template...');
  
  const configTemplate = {
    license_key: 'YOUR_LICENSE_KEY_HERE',
    minecraft: {
      username: 'YOUR_MINECRAFT_LOGIN',
      password: 'YOUR_MINECRAFT_PASSWORD',
      host: 'mc.server.com',
      port: 25565,
      version: '1.20.1'
    },
    bot: {
      name: 'AI_Bot',
      language: 'ru'
    },
    features: {
      pvp: true,
      voice: true,
      autoReconnect: true
    }
  };
  
  try {
    const configPath = path.join(BUILD_CONFIG.releaseDir, 'config.json');
    await fs.writeJson(configPath, configTemplate, { spaces: 2 });
    
    // Также создаем README
    const readmeContent = `# AI Bot Release

## Установка

1. Получите лицензионный ключ на нашем сайте
2. Отредактируйте config.json:
   - Вставьте ваш license_key
   - Укажите логин/пароль Minecraft
   - Укажите IP сервера
3. Запустите AIBot.exe

## Требования

- Windows 10/11 x64
- Интернет-соединение (для проверки лицензии)

## Поддержка

При проблемах с лицензией обращайтесь в поддержку.
`;
    
    await fs.writeFile(path.join(BUILD_CONFIG.releaseDir, 'README.txt'), readmeContent);
    
    logSuccess('config.json template created');
    return true;
  } catch (error) {
    logError(`Failed to create config template: ${error.message}`);
    return false;
  }
}

/**
 * Шаг 7: Очистка временных файлов
 */
async function cleanup() {
  logStep(7, 'Cleaning up temporary files...');
  
  try {
    await fs.remove(BUILD_CONFIG.obfuscatedDir);
    logSuccess('Cleanup complete');
    return true;
  } catch (error) {
    logError(`Cleanup warning: ${error.message}`);
    return true; // Не критично
  }
}

/**
 * Главная функция сборки
 */
async function build() {
  console.log(colors.cyan + '\n╔════════════════════════════════════════════════════════╗' + colors.reset);
  console.log(colors.cyan + '║' + colors.reset + '           AI Bot Release Builder v1.0                ' + colors.cyan + '║' + colors.reset);
  console.log(colors.cyan + '╚════════════════════════════════════════════════════════╝' + colors.reset);
  
  const startTime = Date.now();
  
  const steps = [
    prepareReleaseFolder,
    obfuscateCode,
    preparePackageJson,
    installDependencies,
    buildExecutable,
    createConfigTemplate,
    cleanup
  ];
  
  for (const step of steps) {
    const success = await step();
    if (!success) {
      logError('Build process failed!');
      process.exit(1);
    }
  }
  
  const duration = ((Date.now() - startTime) / 1000).toFixed(2);
  
  console.log(colors.cyan + '\n╔════════════════════════════════════════════════════════╗' + colors.reset);
  console.log(colors.cyan + '║' + colors.green + '                 BUILD SUCCESSFUL!                    ' + colors.cyan + '║' + colors.reset);
  console.log(colors.cyan + '╠════════════════════════════════════════════════════════╣' + colors.reset);
  console.log(colors.cyan + '║' + colors.reset + `  📦 Output: Release/${BUILD_CONFIG.outputExe}`.padEnd(56) + colors.cyan + '║' + colors.reset);
  console.log(colors.cyan + '║' + colors.reset + `  ⚙️  Config: Release/config.json`.padEnd(56) + colors.cyan + '║' + colors.reset);
  console.log(colors.cyan + '║' + colors.reset + `  ⏱️  Time: ${duration}s`.padEnd(56) + colors.cyan + '║' + colors.reset);
  console.log(colors.cyan + '╚════════════════════════════════════════════════════════╝' + colors.reset);
  
  log('\n⚠️  НЕ ЗАБУДЬ:', 'yellow');
  log('   1. Заполнить KEYAUTH_CONFIG в scripts/license-check.js', 'yellow');
  log('   2. Протестировать сборку перед распространением', 'yellow');
  log('   3. Проверить работу лицензии на чистой системе\n', 'yellow');
}

// Запуск сборки
build().catch(error => {
  logError(`Unexpected error: ${error.message}`);
  console.error(error);
  process.exit(1);
});
